### ISSUE TITLE
ModuleNotFoundError: No module named 'win32com' - on Mac for Excel

### ISSUE THREAD

**Issue by gopherpy** [OakwoodAI/Automagica#88]
>>> excel = Excel()
Traceback (most recent call last):
  File "/Users/abc/opt/anaconda3/lib/python3.7/site-packages/Automagica-2.0.7-py3.7.egg/automagica/activities.py", line 3944, in _launch
    import win32com.client
ModuleNotFoundError: No module named 'win32com'

FYI. I have microsoft excel installed on my mac.

Any help is really appreciated.

**Comment by koenvaneijk** [comment]
@gopherpy thank you for raising this. This is because this Python library (win32com) is only available for Windows as those APIs are only available on Windows. You can always try using the Excel File activities, those manipulate Excel files directly on the file, rather than through the application.

We will be providing more meaningful error messages here in the future and is on our shortlist for our next release.

**Comment by koenvaneijk** [comment]
@gopherpy we've included more detailed error messages for all platforms. For each activity you will get an NotImplementedError-exception if it is not supported.
