### ISSUE TITLE
edit scripts - user_secret

### ISSUE THREAD

**Issue by dadokkio** [OakwoodAI/Automagica#94]
Hi,
if I try to edit a script from my machine it requires a "user_secret" (and probably a connection to the portal)
I'm not able to find any info about that in my account, is this a feature only for pro account?

Thanks

**Comment by koenvaneijk** [comment]
@dadokkio if you used the one-click installer for Windows, this should be auto-configured. Your user-secret should be stored somewhere in your users home directory.

Please share with us how you installed Automagica and how you connected your desktop's bot to the Portal. That way we can help you find out where the problem is.

In the meantime, you can always try re-installing through the Portal and then rebooting your machine.

**Comment by dadokkio** [comment]
Ok, I found it!
My ideal plan is to edit the script from a different machine than ones running the script.
I'm more or less able to connect but on linux I'm having some issue on folders.

Thanks

**Comment by koenvaneijk** [comment]
You can copy the `automagica.json` from the root of your user folder on the machine you installed Automagica to the other machine. This is where the user secret is stored.
